### PR TITLE
feat: `fix_verifier_sol` to convert from yul to solidity verifier

### PR DESCRIPTION
**Pull request by alexander-camuto**
Creates a `fix_verifier_sol` function which convert from yul code to solidity verifier. 

The repo also contains Verifier templates in `contracts`, which `fix_verifier_sol` populates with the relevant assembly code. 

Additionally adds integration tests using anvil to test out the pipeline + a fully fledged CI testing pipeline.

### CODE REVIEW

**Comment by CPerezz** [comment]
@alexander-camuto haven't forgotten about this. I just was very busy this week. Will try to review during the next week. Apologies. 
I think @han0110 has the same issue.

**Comment by CPerezz** [comment]
@han0110 does this need review after #2 ?

**Comment by han0110** [comment]
I've reviewed this and it looks good to me, but considering we have https://github.com/privacy-scaling-explorations/snark-verifier/pull/47 to generate solidity directly now, I think this PR's approach would not be favored. So feel free to skip this @CPerezz.

Tho I think we could keep the PR here for a while for visibility, in case some people need it.

**Comment by CPerezz** [comment]
Is there something we can take from this one and profit for the current approach of #2 ??

**Comment by han0110** [comment]
This PR is for `snark-verifier`'s yul output, but #2 is a brand new generator, so perhaps not much.

Just checked again, I found its error handling for `solc` command looks good, so I picked that to #2.

**Pull request closed without merging**
