### PR TITLE
verifyProof function as view as it does not modify storage

### LINKED ISSUE #18: Solidity verifyProof function as view
Hello,
would like to know if there is a reason behind not marking the verifyProof function on the Halo2Verifier as a view, as it does not write anything on storage.
Some ethereum libraries (like ethers js) relies on ABI specification and force to have signer to call that function (using smart contracts interfaces).
If there is no specific reason, I would like fix it.
Thank you!

### PR DESCRIPTION
**Pull request by dibi91**
As discussed on #18 
Noticed bug about rust last version during tests and examples
Close #18

### CODE REVIEW

**Comment by han0110** [comment]
Could you also help create`rust-toolchain` file and fix the version to `1.77.0`? I think it'd resolve the CI issue for now.

**Comment by dibi91** [comment]
Done!

**Comment by dibi91** [comment]
Now it fails because of svm-rs that requires at least 1.8.0 rust version. I can specify in step `Install solc` to use the `smv-rs@0.5.4` that requires rust version greater than 1.7.0 [svm-rs cargo.toml](https://github.com/alloy-rs/svm-rs/blob/v0.5.4/Cargo.toml).

I made a test on a different branch [link](https://github.com/dibi91/halo2-solidity-verifier/actions/runs/11121908909/job/30902042670)

**Review by han0110 — APPROVED** [review]
LGTM, thanks for the contribution.

**Pull request merged**
